// Code generated by goctl. DO NOT EDIT.
// Source: abao.proto

package server

import (
	"context"

	"abao/abao"
	"abao/internal/logic"
	"abao/internal/svc"
)

type AbaoServer struct {
	svcCtx *svc.ServiceContext
	abao.UnimplementedAbaoServer
}

func NewAbaoServer(svcCtx *svc.ServiceContext) *AbaoServer {
	return &AbaoServer{
		svcCtx: svcCtx,
	}
}

func (s *AbaoServer) GetAccount(ctx context.Context, in *abao.GetAccountRequest) (*abao.GetAccountResponse, error) {
	l := logic.NewGetAccountLogic(ctx, s.svcCtx)
	return l.GetAccount(in)
}

func (s *AbaoServer) GetBalance(ctx context.Context, in *abao.GetBalanceRequest) (*abao.GetBalanceResponse, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

func (s *AbaoServer) Transfer(ctx context.Context, in *abao.TransferRequest) (*abao.TransferResponse, error) {
	l := logic.NewTransferLogic(ctx, s.svcCtx)
	return l.Transfer(in)
}

func (s *AbaoServer) GetTranscation(ctx context.Context, in *abao.GetTranscationRequest) (*abao.GetTranscationResponse, error) {
	l := logic.NewGetTranscationLogic(ctx, s.svcCtx)
	return l.GetTranscation(in)
}
