// Code generated by goctl. DO NOT EDIT.
// Source: transfer_lib.proto

package server

import (
	"context"

	"github.com/DwGoing/transfer_lib/internal/logic"
	"github.com/DwGoing/transfer_lib/internal/svc"
	"github.com/DwGoing/transfer_lib/transfer_lib"
)

type TransferLibServer struct {
	svcCtx *svc.ServiceContext
	transfer_lib.UnimplementedTransferLibServer
}

func NewTransferLibServer(svcCtx *svc.ServiceContext) *TransferLibServer {
	return &TransferLibServer{
		svcCtx: svcCtx,
	}
}

func (s *TransferLibServer) GetAccount(ctx context.Context, in *transfer_lib.GetAccountRequest) (*transfer_lib.GetAccountResponse, error) {
	l := logic.NewGetAccountLogic(ctx, s.svcCtx)
	return l.GetAccount(in)
}

func (s *TransferLibServer) GetBalance(ctx context.Context, in *transfer_lib.GetBalanceRequest) (*transfer_lib.GetBalanceResponse, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

func (s *TransferLibServer) Transfer(ctx context.Context, in *transfer_lib.TransferRequest) (*transfer_lib.TransferResponse, error) {
	l := logic.NewTransferLogic(ctx, s.svcCtx)
	return l.Transfer(in)
}

func (s *TransferLibServer) GetTranscation(ctx context.Context, in *transfer_lib.GetTranscationRequest) (*transfer_lib.GetTranscationResponse, error) {
	l := logic.NewGetTranscationLogic(ctx, s.svcCtx)
	return l.GetTranscation(in)
}
