// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: abao.proto

package abao

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Abao_GetAccount_FullMethodName     = "/abao.Abao/GetAccount"
	Abao_GetBalance_FullMethodName     = "/abao.Abao/GetBalance"
	Abao_Transfer_FullMethodName       = "/abao.Abao/Transfer"
	Abao_GetTranscation_FullMethodName = "/abao.Abao/GetTranscation"
)

// AbaoClient is the client API for Abao service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AbaoClient interface {
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	GetTranscation(ctx context.Context, in *GetTranscationRequest, opts ...grpc.CallOption) (*GetTranscationResponse, error)
}

type abaoClient struct {
	cc grpc.ClientConnInterface
}

func NewAbaoClient(cc grpc.ClientConnInterface) AbaoClient {
	return &abaoClient{cc}
}

func (c *abaoClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, Abao_GetAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *abaoClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, Abao_GetBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *abaoClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Abao_Transfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *abaoClient) GetTranscation(ctx context.Context, in *GetTranscationRequest, opts ...grpc.CallOption) (*GetTranscationResponse, error) {
	out := new(GetTranscationResponse)
	err := c.cc.Invoke(ctx, Abao_GetTranscation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AbaoServer is the server API for Abao service.
// All implementations must embed UnimplementedAbaoServer
// for forward compatibility
type AbaoServer interface {
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	GetTranscation(context.Context, *GetTranscationRequest) (*GetTranscationResponse, error)
	mustEmbedUnimplementedAbaoServer()
}

// UnimplementedAbaoServer must be embedded to have forward compatible implementations.
type UnimplementedAbaoServer struct {
}

func (UnimplementedAbaoServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedAbaoServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedAbaoServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedAbaoServer) GetTranscation(context.Context, *GetTranscationRequest) (*GetTranscationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranscation not implemented")
}
func (UnimplementedAbaoServer) mustEmbedUnimplementedAbaoServer() {}

// UnsafeAbaoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AbaoServer will
// result in compilation errors.
type UnsafeAbaoServer interface {
	mustEmbedUnimplementedAbaoServer()
}

func RegisterAbaoServer(s grpc.ServiceRegistrar, srv AbaoServer) {
	s.RegisterService(&Abao_ServiceDesc, srv)
}

func _Abao_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbaoServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abao_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbaoServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Abao_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbaoServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abao_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbaoServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Abao_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbaoServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abao_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbaoServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Abao_GetTranscation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbaoServer).GetTranscation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abao_GetTranscation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbaoServer).GetTranscation(ctx, req.(*GetTranscationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Abao_ServiceDesc is the grpc.ServiceDesc for Abao service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Abao_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abao.Abao",
	HandlerType: (*AbaoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Abao_GetAccount_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Abao_GetBalance_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _Abao_Transfer_Handler,
		},
		{
			MethodName: "GetTranscation",
			Handler:    _Abao_GetTranscation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "abao.proto",
}
