// Code generated by goctl. DO NOT EDIT.
// Source: abao.proto

package abao_client

import (
	"context"

	"abao/abao"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAddressRequest  = abao.GetAddressRequest
	GetAddressResponse = abao.GetAddressResponse
	GetBalanceRequest  = abao.GetBalanceRequest
	GetBalanceResponse = abao.GetBalanceResponse
	TransferRequest    = abao.TransferRequest
	TransferResponse   = abao.TransferResponse

	Abao interface {
		GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error)
		GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
		Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	}

	defaultAbao struct {
		cli zrpc.Client
	}
)

func NewAbao(cli zrpc.Client) Abao {
	return &defaultAbao{
		cli: cli,
	}
}

func (m *defaultAbao) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...grpc.CallOption) (*GetAddressResponse, error) {
	client := abao.NewAbaoClient(m.cli.Conn())
	return client.GetAddress(ctx, in, opts...)
}

func (m *defaultAbao) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	client := abao.NewAbaoClient(m.cli.Conn())
	return client.GetBalance(ctx, in, opts...)
}

func (m *defaultAbao) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	client := abao.NewAbaoClient(m.cli.Conn())
	return client.Transfer(ctx, in, opts...)
}
